name: PR Scan

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches: ['main']
jobs:
  scan:
    name: "Scan PR"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Test and Build Package
      id: test_package
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - run: |
        npm ci
        npm run build
        npx jest --coverage --changedSince=main --coverageThreshold='{"global":{"lines":90}} --passWithNoTests=false' 
        npm test
    - name: OnFail
      if: failure() && steps.test_package.outcome == 'failure'
      uses: andrewmusgrave/automatic-pull-request-review@0.0.5
      with:
        event: DISMISS
        body: "Pull requests must have a minimum of 80% coverage on new code, build successfully, and pass all current unit tests in order to be accepted. Please update and resubmit."


